var scenes_data = {
#	'name': [
#		'local',
#		'emited_signal',
#		'has_config'
#		'audio' => null, 'path', 'continue'
#		'audio_description' => []
#		'has_backpack'
#	]
	'production': [
		'res://scenes/GUI/Production.tscn',
		'end_production',
		false,
		null,
		[],
		false,
	],
	'logo_opening': [
		'res://scenes/GUI/LogoOpening.tscn',
		'end_logo_scene',
		false,
		'res://soundtrack/Loop1 Intro.mp3',
		[],
		false,
	],
	'menu': [
		'res://scenes/GUI/Menu.tscn',
		'end_menu',
		false,
		'continue',
		[],
		false,
	],
	'access01': [
		'res://scenes/FirstAccess/Access01.tscn',
		'end_access01',
		true,
		'res://soundtrack/Loop2-Atualizado.mp3',
		[],
		false,
	],
	'access02': [
		'res://scenes/FirstAccess/Access02.tscn',
		'end_access02',
		true,
		'continue',
		[
			"res://dialogs/audio_description/01_introduction/1_trecho.wav",
			"res://dialogs/audio_description/01_introduction/2_trecho.wav",
			"res://dialogs/audio_description/01_introduction/3_trecho.wav",
			"res://dialogs/audio_description/01_introduction/4_trecho.wav",
		],
		false,
	],
	'character_choice': [
		'res://scenes/FirstAccess/CharacterChoice.tscn',
		'end_choice',
		true,
		'res://soundtrack/Loop3x.mp3',
		[],
		false,
	],
	'diary': [
		'res://scenes/GUI/Diary.tscn',
		'end_diary',
		true,
		'res://soundtrack/Loop5 - Diário.mp3',
		[],
		false,
	],
	'travel_scene': [
		'res://scenes/GUI/TravelScene.tscn',
		'end_travel_scene',
		false,
		null,
		[],
		false,
	],
	'episode_intro':[
		'res://scenes/Introductions/EpisodeIntro.tscn',
		'end_episode_intro',
		true,
		null,
		[],
		false,
	],
	'introd_lavadeiras': [
		'res://scenes/Introductions/Lavadeiras.tscn',
		'introd_lava',
		false,
		null,
		[],
		false,
	],
	'suzana': [
		'res://scenes/dialogs/Suazana.tscn',
		'end_suzana_scene',
		true,
		'continue',
		[],
		false,
	],
	'episodes_selection': [
		'res://scenes/GUI/EpisodeSelection.tscn',
		'end_episode_selection',
		false,
		'continue',
		[],
		false,
	],
	'analyze_photos': [
		'res://scenes/observation/PhotoAnalyze.tscn',
		'end_analyze',
		false,
		null,
		[],
		true,
	],
	'lavadeiras': [
		'res://scenes/ambience/Lavadeiras.tscn',
		'end_lavadeira',
		true,
		'res://soundtrack/Loop4 Lavadeiras.mp3',
		[],
		true,
	],
	'lavadeira_amiga': [
		'res://scenes/dialogs/Lavadeira.tscn',
		'end_lavadeira',
		true,
		'continue',
		[],
		false,
	],
	'intro_multidao': [
		'res://scenes/Introductions/Multidao.tscn',
		'end_multidao',
		true,
		null,
		[],
		false,
	],
	'multidao': [
		'res://scenes/ambience/Multidao.tscn',
		'distractor_selected',
		true,
		"res://soundtrack/hotel diamantina.mp3",
		[],
		false,
	],
	'distractor1_darcy': [
		'res://scenes/dialogs/protesto_bandeirante/Distrator01.tscn',
		'distractor_dialog',
		true,
		'continue',
		[],
		false,
	],
	'distractor2_darcy': [
		'res://scenes/dialogs/protesto_bandeirante/Distrator02.tscn',
		'distractor_dialog',
		true,
		'continue',
		[],
		false,
	],
	'distractor3_darcy': [
		'res://scenes/dialogs/protesto_bandeirante/Distrator03.tscn',
		'distractor_dialog',
		true,
		"res://soundtrack/Levante da Boa Vontade.mp3",
		[],
		false,
	],
	'darcy_speech': [
		'res://scenes/dialogs/Darcy.tscn',
		'end_darcy_speech',
		true,
		"res://soundtrack/Loop Protesto Darcy.mp3",
		[
			"res://dialogs/audio_description/03_darcy_speech/fala_1.wav",
			"res://dialogs/audio_description/03_darcy_speech/fala_2.wav",
			"res://dialogs/audio_description/03_darcy_speech/fala_3.wav",
			"res://dialogs/audio_description/03_darcy_speech/fala_4.wav",
			"res://dialogs/audio_description/03_darcy_speech/fala_5.wav",
			"res://dialogs/audio_description/03_darcy_speech/fala_6.wav",
			"res://dialogs/audio_description/sound_effects/clapping_sound.mp3",
			"res://dialogs/audio_description/03_darcy_speech/fala_7.wav",
			"res://dialogs/audio_description/03_darcy_speech/fala_8.wav",
			"res://dialogs/audio_description/03_darcy_speech/fala_9.wav",
			"res://dialogs/audio_description/03_darcy_speech/fala_10.wav",
			"res://dialogs/audio_description/03_darcy_speech/fala_11.wav",
		],
		false,
	],
	'word_choice': [
		'res://scenes/Minigames/WordSelection.tscn',
		'end_word_selection',
		true,
		null,
		[],
		true,
	],
	'taguatinga_introduction':[
		'res://scenes/Introductions/TaguaIntroduction.tscn',
		'end_taguatinga_introduction',
		false,
		null,
		[],
		false,
	],
	'Taguatinga': [
		'res://scenes/ambience/Taguatinga.tscn',
		'end_taguatinga',
		true,
		'res://soundtrack/Loop4 Lavadeiras.mp3',
		[],
		true,
	],
	'jose_dialog':[
		'res://scenes/dialogs/investigação_taguatinga/JoséMiguel.tscn',
		'end_jose_dialog',
		false,
		'continue',
		[],
		false,
	],
	'policial_distrator_dialog':[
		'res://scenes/dialogs/investigação_taguatinga/PolicialDistrator.tscn',
		'end_policial_distrator_dialog',
		false,
		'continue',
		[],
		false,
	],
	'chefe_de_policia_dialog':[
		'res://scenes/dialogs/investigação_taguatinga/ChefeDePolicia.tscn',
		'end_chefe_de_policia_dialog',
		false,
		'continue',
		[],
		true,
	],
	'distrator_trabalhador_dialog':[
		'res://scenes/dialogs/investigação_taguatinga/DistratorTrabalhador.tscn',
		'end_distrator_trabalhador_dialog',
		false,
		'continue',
		[],
		false,
	],
	'raulino_dialog':[
		'res://scenes/dialogs/investigação_taguatinga/Raulino.tscn',
		'end_raulino_dialog',
		false,
		'continue',
		[],
		true,
	],
	'folheto_raulino':[
		'res://scenes/ambience/FolhetoRaulino.tscn',
		'end_folheto_raulino',
		false,
		null,
		[],
		false,
	],
	'plano_piloto_intro':[
		'res://scenes/Introductions/PlanoPilotointro.tscn',
		'end_plano_piloto_intro',
		false,
		null,
		[],
		true,
	],
	'israel_dialog':[
		'res://scenes/dialogs/Esplanada/IsraeldaSilva.tscn',
		'end_israel_dialog',
		false,
		null,
		[],
		true,
	],
	'ranieri_jornalista_dialog':[
		'res://scenes/dialogs/Esplanada/RanieriJornalista.tscn',
		'end_ranieri_jornalista_dialog',
		false,
		null,
		[],
		true,
	],
	'israel_professora_dialog':[
		'res://scenes/dialogs/Esplanada/IsraelProfessora.tscn',
		'end_israel_professora_dialog',
		false,
		null,
		[],
		true,
	],
	'word_selection_2':[
		'res://scenes/Minigames/WordSelection2.tscn',
		'end_word_selection_2',
		false,
		null,
		[],
		true,
	]
}
